### ISSUE TITLE
Release still false after tagging

### ISSUE THREAD

**Issue by d3vhound** [samuelmeuli/action-electron-builder#11]
Followed the docs and copied your workfile code and release commit workflow. Still getting `release: false` for some reason.

<img width="860" alt="Screen Shot 2020-01-24 at 1 31 40 PM" src="https://user-images.githubusercontent.com/17565159/73097897-dd393680-3ead-11ea-9b09-7fc4752ae119.png">

**Comment by samuelmeuli** [comment]
Can you see whether your tag has been pushed successfully ("Releases" tab on GitHub)?

**Comment by goyney** [comment]
I am also seeing this. My first release was fine, but I cannot get any other releases to happen. The tags are created correctly, but `release: false` is always the case now.

**Comment by samuelmeuli** [comment]
Please check the following:

1. Make sure your tag is in the format `v*` and it's pushed correctly.
2. You're looking at the correct workflow execution (one triggered by a tag push, not a commit push). Tagged commits will have two corresponding workflows.

If this doesn't help: The `release` value is set to `${{ startsWith(github.ref, 'refs/tags/v') }}` in the README example, so this would indicate that the actual `ref` is different. Could you try logging the `ref` and checking if/why it doesn't start with `refs/tags/v`?

**Comment by goyney** [comment]
There was the problem. I specified branches for `push`, which begins ignoring tag pushes. I had to explicitly add those.

```
  push:
    tags:
      - v*
```

That solved my issue. Perhaps @d3vhound has a similar issue.
