### ISSUE TITLE
Option to configure build script name

### ISSUE THREAD

**Issue by leclercb** [samuelmeuli/action-electron-builder#12]
Thanks for the action script !
It would be nice to be able to configure the build script name.

For the moment, this is how my scripts are looking, it's pretty hard to get the git hash via a command that works on every system. So I created two build scripts:

`
"build": "REACT_APP_GIT_COMMIT_HASH=$(git rev-parse --short HEAD) craco build",
"build:github": "craco build",
`

And in the build and release steps of my workflow I added:

`
env:
          REACT_APP_GIT_COMMIT_HASH: "${{ github.sha }}"
`

PS: The script is working fine, but no artifact is generated once the build is complete, is it normal ?

Thanks

**Comment by samuelmeuli** [comment]
Yes, let's introduce an option for this (maybe called `build_script` or `build_script_name`). @leclercb Would you be interested in opening a PR?

Regarding the missing artifacts, have you set the `release` option? By default, no release is created.

**Comment by leclercb** [comment]
PR created.

To be honest, I didn't try the release yet as I still need to test the certificates option.
What I mean, is that GitHub Actions is able to produce artifacts, that you can download when looking at the process.
Adding an extra step in my yaml workflow to publich the artifact could do the trick.
I don't know if it's feasible, but if this could be automatically called by the "action-electron-builder" it would be even better.

I hope it was clearer.

**Comment by samuelmeuli** [comment]
Now I understand. You're right, this isn't currently implemented. Could adding a https://github.com/actions/upload-artifact step after the Electron Builder Action work? If it's really that simple, I don't think this should be included in the action, but added to the README or a docs page.

**Comment by leclercb** [comment]
Actually, it's not that simple, because you need to know the name of the files generated, depending on the OS, multiple artifact can be build and currently the upload-artifact actions doesn't allow regex or patterns for multiple files.
That's why, if "action-electron-builder" could call them, knowing the right name of every file created and then upload them, it would be much easier.

**Comment by samuelmeuli** [comment]
I agree on the file renaming. But I don't know if uploading artifacts from within an action is already possible; I'm not sure if the API is already publicly available (see https://github.com/actions/upload-artifact/issues/7#issuecomment-566114993 and https://developer.github.com/v3/actions/artifacts).

**Comment by samuelmeuli** [comment]
This is tracked by #14
