### ISSUE TITLE
Upload build artifacts

### ISSUE THREAD

**Issue by samuelmeuli** [samuelmeuli/action-electron-builder#14]
The action should upload the packaged apps to GitHub (if such an API is already available) or at least give predictable names to the files so they can be uploaded with https://github.com/actions/upload-artifact.

See the previous discussion in #12.

PRs are welcome :)

**Comment by leclercb** [comment]
After some tests, it might actually not be needed.
When the GitHub upload-artifact action will support pattern/regex/globs it will be easier, but it already possible to make something useful.

The most simple is adding this at the end of the script, but be aware that it will create one big file which can quickly take more than 1go


`
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-app
          path: dist
`


Or better version is this one, which will only take the binaries and not the unpacked folders and create an artifact per platform:

`
      - name: Move Files
        shell: bash
        run: |
          mkdir dist-linux dist-mac dist-win
          mv dist/latest-linux.yml dist/*.AppImage dist/*.tar.gz dist/*.snap dist-linux
          mv dist/latest-mac.yml dist/*.dmg dist/*.dmg.blockmap dist-mac
          mv dist/latest.yml dist/*.exe dist/*.exe.blockmap dist-win

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-app-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-app-mac
          path: dist-mac

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: my-app-win
          path: dist-win
`

I think this issue can be closed :)
