### ISSUE TITLE
"Operation canceled" when building Windows app on macOS

### ISSUE THREAD

**Issue by teknoalex** [samuelmeuli/action-electron-builder#18]
Everytime I use the action, the operation gets canceled after downloading electron stuff.

Output:

Running the build script…

> pushups-reminder@1.0.0 build /Users/runner/runners/2.165.2/work/pushup-reminder/pushup-reminder
> electron-builder --windows --linux

  • electron-builder  version=22.4.1 os=19.3.0
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=linux arch=x64 electron=8.1.1 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-linux-x64.zip size=71 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-linux-x64.zip duration=1.906s
  • building        target=AppImage arch=x64 file=dist/pushups-reminder-1.0.0.AppImage
  • packaging       platform=win32 arch=x64 electron=8.1.1 appOutDir=dist/win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip size=71 MB parts=8
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=878ms
  • downloaded      url=https://github.com/electron/electron/releases/download/v8.1.1/electron-v8.1.1-win32-x64.zip duration=2.994s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z size=5.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/winCodeSign-2.6.0/winCodeSign-2.6.0.7z duration=1.932s
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-4.0.1-mac/wine-4.0.1-mac.7z size=19 MB parts=3
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/wine-4.0.1-mac/wine-4.0.1-mac.7z duration=684ms
##[error]The operation was canceled.

**Comment by samuelmeuli** [comment]
Could you please share your GitHub Actions workflow?

You can format your logs in GitHub Issues with Markdown: https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax

**Comment by samuelmeuli** [comment]
> electron-builder --windows --linux

This looks wrong. Please follow [these steps](https://github.com/samuelmeuli/action-electron-builder#setup) in the README.
