### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by mifi** [samuelmeuli/action-electron-builder#21]
I'm getting this error pretty often during the upload phase.

```
  • building        target=DMG arch=x64 file=dist/LosslessCut-mac.dmg
  • building block map  blockMapFile=dist/LosslessCut-mac.dmg.blockmap
  • uploading       file=LosslessCut-mac.dmg.blockmap provider=GitHub
  • uploading       file=LosslessCut-mac.dmg provider=GitHub
  ⨯ socket hang up  stackTrace=
                      Error: socket hang up
                          at connResetException (internal/errors.js:608:14)
                          at TLSSocket.socketOnEnd (_http_client.js:460:23)
                          at TLSSocket.emit (events.js:322:22)
                          at endReadableNT (_stream_readable.js:1187:12)
                          at processTicksAndRejections (internal/process/task_queues.js:84:21)
  • overwrite published file  file=LosslessCut-mac.dmg.blockmap reason=already exists on GitHub
  • overwrite published file  file=LosslessCut-mac.dmg reason=already exists on GitHub
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
child_process.js:660
    throw err;
    ^

Error: Command failed: yarn run electron-builder --mac --publish always
```

I realize it's probably GitHub's fault for having unstable infrastructure, but I'm wondering if it's possible to implement some retry? Or maybe it needs to be done in electron-builder

**Comment by samuelmeuli** [comment]
Unfortunately, this happens to me too every now and then. Re-running the workflow should do the trick. I also think this should be handled by `electron-builder`, especially because according to the docs, running it in CI seems to be a common use case.

**Comment by craftycram** [comment]
Hey, I'm having the same issue for a while now. I'm building my app for macOS, Windows and Ubuntu and randomly one of the tasks fails due to the socket error, which causes the other two to get cancelled as well.
I thought that maybe #28 could fix that issue, because it will automatically try again, but sadly that didn't help as well.
Is there a way to automatically retry on failure or is there a new and better fix for that issue?

**Comment by mandrasch** [comment]
@craftycram See https://github.com/electron-userland/electron-builder/issues/4940 for actual state of issue :)

**Comment by craftycram** [comment]
@mandrasch 

thanks for the info
