### ISSUE TITLE
add retry option

### ISSUE THREAD

**Issue by juliangruber** [samuelmeuli/action-electron-builder#28]
Lately some builds have failed because of errors on apple servers, and we needed to manually restart these builds. It would be great if this action had an option to restart builds automatically, for a certain number of max retries.

**Comment by samuelmeuli** [comment]
Agreed, I've encountered similar problems. I'm open to PRs in case anyone wants to implement this feature :)

**Comment by juliangruber** [comment]
I'm going to work on this now 👋

**Comment by jessedp** [comment]
This is just a +1 for this being merged.

I've had to put `yarn install` for my builds on repeat with [Travis](https://travis-ci.com/github/jessedp/tablo-tools-electron/jobs/346979685) and now [here](https://github.com/jessedp/tablo-tools-electron/runs/770791355?check_suite_focus=true). Obviously this is **not** a problem with this action, but the retries could help "fix" it like they did with Travis.
