### ISSUE TITLE
Release on another Repro

### ISSUE THREAD

**Issue by ScarVite** [samuelmeuli/action-electron-builder#64]
I wanted to ask if it is possible to have the workflow running on one private repro and have it released on a public one

**Comment by scope2229** [comment]
This you do with electron builder not the github action. Basically in your package.json or where you have electron-builder configured change the publish repo to the public one.

`
"build": {
    "publish": {
        "provider": "github",
        "repo": "publicrepo",
        "owner": "name",
        "releaseType": "release"
    }
} 
`

**Comment by samiulhsohan** [comment]
@scope2229 how can i give permission to release to another repo? I'm getting 403 error 
```
HttpError: 403 Forbidden
"method: post url: https://api.github.com/repos/samiulhsohan/printkoro-release/releases\n\n          Data:\n          {\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#create-a-release\"}\n          "
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 24 Mar 2022 13:56:36 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "136",
  "x-github-media-type": "github.v3; format=json",
  "x-ratelimit-limit": "1000",
  "x-ratelimit-remaining": "998",
  "x-ratelimit-reset": "1648133795",
  "x-ratelimit-used": "2",
  "x-ratelimit-resource": "core",
  "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
  "access-control-allow-origin": "*",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
  "content-security-policy": "default-src 'none'",
  "vary": "Accept-Encoding, Accept, X-Requested-With",
  "x-github-request-id": "0401:4209:4B31C3:ABD932:623C7894",
  "connection": "close"
}
    at createHttpError (D:\a\printjob\printjob\node_modules\builder-util-runtime\src\httpExecutor.ts:30:10)
    at IncomingMessage.<anonymous> (D:\a\printjob\printjob\node_modules\builder-util-runtime\src\httpExecutor.ts:1[97](https://github.com/samiulhsohan/printjob/runs/5677291334?check_suite_focus=true#step:5:97):13)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by scope2229** [comment]
> @scope2229 how can i give permission to release to another repo? I'm getting 403 error 
> ```
> HttpError: 403 Forbidden
> "method: post url: https://api.github.com/repos/samiulhsohan/printkoro-release/releases\n\n          Data:\n          {\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#create-a-release\"}\n          "
> Headers: {
>   "server": "GitHub.com",
>   "date": "Thu, 24 Mar 2022 13:56:36 GMT",
>   "content-type": "application/json; charset=utf-8",
>   "content-length": "136",
>   "x-github-media-type": "github.v3; format=json",
>   "x-ratelimit-limit": "1000",
>   "x-ratelimit-remaining": "998",
>   "x-ratelimit-reset": "1648133795",
>   "x-ratelimit-used": "2",
>   "x-ratelimit-resource": "core",
>   "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
>   "access-control-allow-origin": "*",
>   "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
>   "x-frame-options": "deny",
>   "x-content-type-options": "nosniff",
>   "x-xss-protection": "0",
>   "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
>   "content-security-policy": "default-src 'none'",
>   "vary": "Accept-Encoding, Accept, X-Requested-With",
>   "x-github-request-id": "0401:4209:4B31C3:ABD932:623C7894",
>   "connection": "close"
> }
>     at createHttpError (D:\a\printjob\printjob\node_modules\builder-util-runtime\src\httpExecutor.ts:30:10)
>     at IncomingMessage.<anonymous> (D:\a\printjob\printjob\node_modules\builder-util-runtime\src\httpExecutor.ts:1[97](https://github.com/samiulhsohan/printjob/runs/5677291334?check_suite_focus=true#step:5:97):13)
>     at IncomingMessage.emit (node:events:532:35)
>     at endReadableNT (node:internal/streams/readable:1346:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> ```

Did you add your gh_token to be able to push to your public repo ??

**Comment by samiulhsohan** [comment]
Yeah. I have only added `GH_TOKEN` in the **_Actions secrets_** to the repo from where the action is running. Do I need to add any other configs?

**Comment by scope2229** [comment]
> Yeah. I have only added `GH_TOKEN` in the **_Actions secrets_** to the repo from where the action is running. Do I need to add any other configs?

Have you added it to the secrets section in your repo's settings? Also is the token valid? Is the repo your trying to push to public ?

**Comment by samiulhsohan** [comment]
It's working now. I confused myself with the token. I didn't realize I need to update/set the `github_token` in the `action.yml` file as the readme says _"No need to define this secret in the repo settings"_.
