### ISSUE TITLE
Add option override if yarn / npm is used

### ISSUE THREAD

**Issue by hrueger** [samuelmeuli/action-electron-builder#69]
I have a strange bug with `electron-builder`. If it is started with npm or npx, it just freezes at some point. However, when started with yarn, it works fine.
So I'd like to tell the action to definitely use yarn, even if the `package-lock.json` file exists. Is that possible?

My current workaround is to rename the package-lock.json file to something else before running this action, but that's not very practicable.

**Comment by scope2229** [comment]
You need to pick between Yarn and NPM, don't use both. It can cause some annoying issues.

**Comment by hrueger** [comment]
OK, I understand that it is quite a weird feature that I'm requesting. So never mind, for me it works that way.
