### ISSUE TITLE
Cannot Build MacOS App

### ISSUE THREAD

**Issue by Afanyiyu** [samuelmeuli/action-electron-builder#8]
Sorry to trouble you. The action cannot build app for MacOS while it works perfectly on other matrix. 
Workflow: https://github.com/dd-center/Cator/blob/master/.github/workflows/shellbuild.yml
Failed Action: https://github.com/dd-center/Cator/runs/381204962
package.json: https://github.com/dd-center/Cator/blob/master/packages/cator-shell/package.json

```
Error: Exit code: 2. Command failed: /usr/bin/perl /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/t-M2nRmP/1-dmgProperties.pl
Can't locate Mac/Memory.pm in @INC (you may need to install the Mac::Memory module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.4 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/t-M2nRmP/1-dmgProperties.pl line 4.
BEGIN failed--compilation aborted at /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/t-M2nRmP/1-dmgProperties.pl line 4.
```

Google says `brew unlink perl` might be useful but I don't know how to do. 
Thanks.

**Comment by samuelmeuli** [comment]
Seems like updating `electron-builder` should fix this: https://github.com/electron-userland/electron-builder/issues/3990. This action requires `electron-builder` v22+ anyway.

**Comment by Afanyiyu** [comment]
![image](https://user-images.githubusercontent.com/20179549/72151248-af9aba80-33e2-11ea-9b00-9764f16d8f6b.png)
Thanks a lot!!!
