### ISSUE TITLE
Actions keep skipping publishing.

### ISSUE THREAD

**Issue by Wolff51** [samuelmeuli/action-electron-builder#98]
Hey there, 

I'm trying to build my react / Electron app

This is my package.json : 
 "version": "0.4.10",
"scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "electrondev": "set ELECTRON_IS_DEV=1 && electron .",
  },
  "build": {
    "appId": "com.electron.myapp",
    "productName": "Sherlock Studio Beta",
    "extraResources": [
      {
        "from": "python",
        "to": "python"
      }
    ],
    "files": [
      "build//*",
      "node_modules//*"
    ],
    "directories": {
      "buildResources": "public"
    },
    "mac": {
      "icon": "public/images/iconemac.png",
      "target": "dmg"
    },
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "icon": "public/images/icone.png",
      "target": [
        "nsis"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "license": "LICENSE.txt"
    },
    "linux": {
      "icon": "public/images/icone.png",
      "target": "deb"
    }
  },

I always follow the electron github actions steps 

But most of the time, when i push i have this error message : 

• skipped publishing  file=MyApp-0.4.10.dmg.blockmap reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v0.4.10 version=0.4.10
  • skipped publishing  file=MyApp-0.4.10.dmg reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v0.4.10 version=0.4.10
  • skipped publishing  file=latest-mac.yml reason=release doesn't exist and not created because "publish" is not "always" and build is not on tag tag=v0.4.10 version=0.4.10

If anyone can help, i did not find any solution yesterday and this morning ..

**Comment by electr0de** [comment]
Having the same exact problem.

**Comment by ghost** [comment]
I'm having the same problem, can you share what you done to mark this as completed?

**Comment by Wolff51** [comment]
Hi, 

It's been a while since I fixed this problem. As far as I remember, I just re-set up all my apps following the documentation. You need to follow every step written by the author, mainly the releasing part (git tag, git commit, etc.). If you have a clean setup, every push will release correctly.

I was just stuck in a wrong setup !
